language: 'node_js'
node_js:
- 'stable'

env:
  global:
  - YANDEX_METRIKA_ID=47230383
  - GOOGLE_ANALYTICS_ID=UA-63968909-10
  - SENTRY_DSN=https://c394c49fafda419598e3d47991816fc7@sentry.io/268009
  - PUBLIC_DOMAIN=reso.lith.pw
  - YANDEX_SITE_VERIFICATION_TOKEN=12b37e57da29060c
  - GOOGLE_SITE_VERIFICATION_TOKEN=N8zcDQCuwg72t6DFlB8xTFYdWVEUR9dEGCtFzKgQTJ0

cache:
  directories:
  - 'node_modules'
  - 'dist'

jobs:
  include:
  - stage: 'lint'
    script:
    - 'yarn lint'

  - stage: 'build'
    script:
    - 'yarn build'
    - 'echo "$PUBLIC_DOMAIN" >> dist/CNAME'

  - stage: 'deploy'
    deploy:
      provider: 'pages'
      skip-cleanup: 'true'
      github-token: $GITHUB_TOKEN
      keep-history: true
      local_dir: 'dist'
      on:
        branch: 'master'
