language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- echo "$PUBLIC_DOMAIN" >> dist/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
env:
  global:
  - YANDEX_METRIKA_ID=47230383
  - GOOGLE_ANALYTICS_ID=UA-63968909-10
  - SENTRY_DSN=https://c394c49fafda419598e3d47991816fc7@sentry.io/268009
  - PUBLIC_DOMAIN=reso.lith.pw
  - YANDEX_SITE_VERIFICATION_TOKEN=12b37e57da29060c
  - GOOGLE_SITE_VERIFICATION_TOKEN=N8zcDQCuwg72t6DFlB8xTFYdWVEUR9dEGCtFzKgQTJ0
